version:         2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image:   circleci/node:7.10

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:     yarn install

      - save_cache:
          paths:
            - node_modules
          key:   v1-dependencies-{{ checksum "package.json" }}

      # build reference images
      - run:     yarn run reference

      # run tests
      - run:     yarn run test

      - store_test_results:
          path:  ~/project/tests

      - store_artifacts:
          path: ~/project/tests
